### ISSUE TITLE
Error in launching run_evaluation.py

### ISSUE THREAD

**Issue by GattiMh** [dellacortelab/milcdock#3]
Hello,

I've tried to run the example provided as `python run_evaluation.py` but I get these errors:

```
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.


Any help with this? Working on Mac by the way.

Thanks a lot

```

**Comment by jacobastern** [comment]
I'm not sure the source of your error. 

However, we should soon (in less than 1 week) have a fully-functional Docker-ized workflow so that you can run MILCDock across platforms with all dependencies pre-packaged. I will reply in this thread when there is an update.

**Comment by GattiMh** [comment]
> 

Thanks! Looking forward to it!

**Comment by jacobastern** [comment]
The repo is updated - all info you need to run the code, including docking with all five programs, ml inference, and ml training, is available in the README. The only requirement is Docker. Let me know if you have any questions.
